<Project>

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Web.Website" />
    <PackageReference Include="StyleCop.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\stylecop.json" />
  </ItemGroup>

  <PropertyGroup>
    <Authors>Dave Woestenborghs</Authors>
    <Product>Our.Umbraco.MultiLanguageTextbox</Product>
    <Company />
    <PackageProjectUrl>https://github.com/dawoe/umbraco-multilanguage-textbox</PackageProjectUrl>
    <RepositoryUrl>https://github.com/dawoe/umbraco-multilanguage-textbox</RepositoryUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageIconUrl />
    <Description>This property editor gives you a textbox per configured language in Umbraco. Ideal for managing multilanguage text content on media items.</Description>
    <PackageTags>umbraco</PackageTags>
    <RepositoryType>git</RepositoryType>
    <Copyright>Copyright &amp;#169; Dave Woestenborghs and contributors.</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <AssemblyVersion>17.0.1</AssemblyVersion>
    <VersionPrefix>17.0.1</VersionPrefix>
    <InformationalVersion>17.0.1</InformationalVersion>
  </PropertyGroup>


  <ItemGroup>
    <None Include="..\..\..\icon\icon.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
</Project>
