$RootDir = Split-Path -Path $CurrentDir -Parent
$TestSitesFolderName = "testsites"
$TestSitesFolder = "$RootDir\$TestSitesFolderName"
$TestProjectName = "V10"
$PackageName = "Our.Umbraco.MultiLanguageTextbox"
$SolutionName = "Our.Umbraco.MultiLanguageTextbox"
$SourceDir = "$RootDir\src"
$UmbracoVersion = "10.0.0"
$StarterKitVersion = "10.0.0"